ucb_site_configuration:
  path: '/admin/config/cu-boulder'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'CU Boulder site settings'
    _description: 'Change CU Boulder site-specific settings.'
  requirements:
    _permission: administer ucb site
  options:
    _admin_route: true

ucb_site_configuration.appearance_form:
  path: '/admin/config/cu-boulder/appearance'
  defaults:
    _form: '\Drupal\ucb_site_configuration\Form\SettingsForm'
    _title: Appearance
  requirements:
    _permission: administer ucb site
  options:
    _admin_route: true

ucb_site_configuration.contact_info_form:
  path: '/admin/config/cu-boulder/contact-info'
  defaults:
    _form: '\Drupal\ucb_site_configuration\Form\ContactInfoForm'
    _title: Contact info
  requirements:
    _permission: administer ucb site
  options:
    _admin_route: true

ucb_site_configuration.external_service_settings_form:
  path: '/admin/config/cu-boulder/services'
  defaults:
    _form: '\Drupal\ucb_site_configuration\Form\ExternalServiceSettingsForm'
    _title: Third-party services
  requirements:
    _permission: administer ucb site
  options:
    _admin_route: true
