name: CU Boulder Site Configuration
description: 'Allows CU Boulder site administrators to configure site-specific settings.'
core_version_requirement: ^8.8 || ^9
type: module
version: '1.1'
package: CU Boulder
dependencies:
  - block
  - system
