ucb_site_configuration:
  title: CU Boulder site settings
  description: 'Change CU Boulder site-specific settings.'
  route_name: ucb_site_configuration
  parent: system.admin_config
  weight: 0

ucb_site_configuration.general_form:
  title: General
  description: 'Modify general site information.'
  route_name: ucb_site_configuration.general_form
  parent: ucb_site_configuration
  weight: 0
ucb_site_configuration.appearance_form:
  title: Appearance and layout
  description: 'Change the appearance, layout, or formatting options of the site.'
  route_name: ucb_site_configuration.appearance_form
  parent: ucb_site_configuration
  weight: 1
ucb_site_configuration.content_types_form:
  title: Content types
  description: 'Change settings for specific content types.'
  route_name: ucb_site_configuration.content_types_form
  parent: ucb_site_configuration
  weight: 2
ucb_site_configuration.contact_info_form:
  title: Contact info
  description: 'Modify the contact info for the site as it appears in the site footer.'
  route_name: ucb_site_configuration.contact_info_form
  parent: ucb_site_configuration
  weight: 3
ucb_site_configuration.external_services:
  title: Third-party services
  description: 'Configure third-party services to be used on the site.'
  route_name: entity.ucb_external_service_include.collection
  parent: ucb_site_configuration
  weight: 4
