name: CU Boulder Site Configuration
description: 'Allows CU Boulder site administrators to configure site-specific settings.'
core_version_requirement: ^9 || ^10
type: module
version: '2.3'
package: CU Boulder
dependencies:
  - block
  - node
  - ucb_admin_menus
  - system
