ucb_site_configuration.external_service_includes.*:
  type: config_entity
  label: 'External service include'
  mapping:
    id:
      type: string
      label: 'Identifier'
    label:
      type: label
      label: 'Label'
    service_name:
      type: string
      label: 'Service name'
    sidewide:
      type: boolean
      label: 'Sitewide'
    nodes:
      type: sequence
      label: 'Content pages'
      sequence:
        type: integer
        label: 'Content page identifier'
