ucb_site_configuration.external_service_includes.*:
  type: config_entity
  label: 'External service include'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    service_name:
      type: string
      label: 'Service name'
