ucb_site_configuration.newsletter_mjml:
  type: config_object
  label: 'Newsletter MJML settings'
  mapping:
    api_endpoint:
      type: string
      label: 'MJML render endpoint'
    application_id:
      type: string
      label: 'MJML application ID'
    secret_key:
      type: string
      label: 'MJML secret key'

ucb_site_configuration.external_service_includes.*:
  type: config_entity
  label: 'External service include'
  mapping:
    id:
      type: string
      label: 'Identifier'
    label:
      type: label
      label: 'Label'
    service_name:
      type: string
      label: 'Service name'
    service_settings:
      type: sequence
      label: 'Service settings'
      sequence:
        type: string
        label: 'Service setting mapping'
    sidewide:
      type: boolean
      label: 'Sitewide'
    content_ediing_enabled:
      type: boolean
      label: 'Content editing enabled'
    nodes:
      type: sequence
      label: 'Content pages'
      sequence:
        type: string
        label: 'Content page identifier'
